import assert from "assert";
import path from "path";
import ResourceLocation from "../index";

const obj1 = new ResourceLocation("namespace", "path");
const obj2 = new ResourceLocation("path");
const obj3 = new ResourceLocation("namespace:path");
assert.strictEqual(obj1.namespace, "namespace");
assert.strictEqual(obj1.path, "path");
assert.strictEqual(obj1.toString(), "namespace:path");
assert.strictEqual(obj2.namespace, "minecraft");
assert.strictEqual(obj2.path, "path");
assert.strictEqual(obj2.toString(), "minecraft:path");
assert.deepStrictEqual(obj3, obj1);
assert.throws(() => new ResourceLocation("Path"));
assert.throws(() => new ResourceLocation("Namespace", "path"));
assert.strictEqual(obj1.toPath(""), path.join("namespace", "path"));
assert.strictEqual(obj1.toPath("a"), path.join("namespace", "a", "path"));
assert.strictEqual(obj1.toPath("a/b"), path.join("namespace", "a", "b", "path"));
assert.ok(obj1.is("namespace:path"));
assert.ok(obj2.is("path"));
assert.ok(obj3.is(obj1));
assert.ok(!obj3.is(obj2));
assert.deepStrictEqual(ResourceLocation.from(obj1), obj1);
assert.deepStrictEqual(ResourceLocation.from("namespace:path"), obj1);
assert.deepStrictEqual(ResourceLocation.from("path"), obj2);
